InputMap = {
    x = "u",
    y = "i",
    a = "z",
    b = "x",
    up = "up",
    lk5 = "end",
    lk1 = "home",
    left = "left",
    down = "down",
    lk2 = "pageup",
    lk3 = "lshift",
    right = "right",
    menu = "escape",
    select = "space",
    lk4 = "pagedown",
    start = "kpenter",
}
